runtime: nodejs20
env: standard

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: dist/index.html # Vueアプリケーションのビルドされたディレクトリを指定
    upload: dist/index.html # ローカルのディレクトリ構造に合わせて指定

  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)


# デプロイ方法
# 1.build
  # npm run build
# 2.deploy
  # gcloud app deploy